version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tiny-shop-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: tiny_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - tiny-shop-network-dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tiny-shop-backend-dev
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: tiny_shop
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - tiny-shop-network-dev

volumes:
  postgres_data_dev:

networks:
  tiny-shop-network-dev:
    driver: bridge
