version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tiny-shop-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tiny_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tiny-shop-network

volumes:
  postgres_data:

networks:
  tiny-shop-network:
    driver: bridge
